# Generated by Django 6.1.2 on 2026-10-07 05:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import kiosk.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.01')), ('price__lte', Decimal('999999.99'))), name='product_price_range')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=kiosk.models.new_reference, editable=False, max_length=35, unique=True, validators=[django.core.validators.RegexValidator('^CT-[0-9a-f]{32}$', 'Invalid transaction reference.')])),
                ('payment_attempt', models.UUIDField(editable=False, unique=True)),
                ('customer_context', models.UUIDField(editable=False)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('qr', 'QR Payment'), ('card', 'Credit/Debit Card')], max_length=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('change', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('payment_method__in', ['cash', 'qr', 'card'])), name='sale_payment_method_valid'), models.CheckConstraint(condition=models.Q(('total__gte', Decimal('0.01')), ('total__lte', Decimal('99999999.99'))), name='sale_total_range'), models.CheckConstraint(condition=models.Q(('amount_paid__gte', models.F('total')), ('amount_paid__lte', Decimal('99999999.99'))), name='sale_paid_covers_total'), models.CheckConstraint(condition=models.Q(('change__gte', Decimal('0.00')), ('change__lte', Decimal('99999999.99'))), name='sale_change_range'), models.CheckConstraint(condition=models.Q(('payment_method', 'cash'), models.Q(('amount_paid', models.F('total')), ('change', Decimal('0.00'))), _connector='OR'), name='sale_noncash_exact_payment')],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='kiosk.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='kiosk.transaction')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 99)), name='sale_item_quantity_range'), models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.01')), ('unit_price__lte', Decimal('999999.99'))), name='sale_item_price_range'), models.CheckConstraint(condition=models.Q(('subtotal__gte', Decimal('0.01')), ('subtotal__lte', Decimal('99999999.99'))), name='sale_item_subtotal_range')],
            },
        ),
    ]
